#!/data/data/com.termux/files/usr/bin/bash

LOCAL_HOST="seymour"
REMOTE_HOST="clews.pro"
LOCAL_USER="b4t"
REMOTE_USER="b4t"

echo "Attempting to connect locally to $LOCAL_USER at $LOCAL_HOST..."
if ! ssh ${LOCAL_USER}@${LOCAL_HOST}; then
	echo "Local connection failed."
	echo "Attempting to connect remotely to $REMOTE_USER at $REMOTE_HOST..."
	if ! ssh -t ${REMOTE_USER}@${REMOTE_HOST} "ssh ${LOCAL_USER}@${LOCAL_HOST}"; then
		echo "Remote connection failed."
		echo "Unable to connect."
	fi
fi


