#!/data/data/com.termux/files/usr/bin/bash

## Termux script for use on phone or tablet.
## Connects to p0wer server over local network if available.
## If not available, attempts connection remotely.
## Once connected, runs $COMMAND
## Intended to run p0wer programme on p0wer server to switch on/off a selected mains point.

LOC_USER="osmc"			# User for attempting local network connection (faster).
LOC_SERVER="brain-slug"		# Hostname for attempting local network connection.
REM_USER="b4t"			# User for attempting remote network connection (if local fails)
REM_SERVER="clews.pro"		# Hostname for remote network connection.
COMMAND="/home/osmc/bin/tv_on.sh"	# Command to run on server.

echo "Desired command on target: \"${COMMAND}\""
echo "Attempting local connection."
ssh ${LOC_USER}@${LOC_SERVER} "${COMMAND}"
if [ $? = '0' ]; then						# If local connection succeeds.
	echo "Command successfully sent locally."
else								# Local connection timed out.
	echo "Unable to make local connection.  Attempting remote connection"
	ssh ${REM_USER}@${REM_SERVER} "ssh ${LOC_USER}@${LOC_SERVER} "${COMMAND}""
	if [ $? = '0' ]; then					# If remote connection succeeds.
		echo "Command successfully sent remotely."
	else							# Remote connection timed out.
		echo "Unable to connect.  Quitting."
	fi
fi

