---
- name: Configure zoidberg.
  hosts: zoidberg
  become: yes
  gather_facts: true

  handlers:
    - import_tasks: handlers/handlers.yml

  roles:
    - common
    - secure
    - headless
    - docker
    - web_apps
    - polly
